### ISSUE TITLE
Allow setting a html_help

### ISSUE THREAD

**Issue by aesislabs** [jbtronics/settings-bundle#18]
Hi,

Great much needed bundle. It would be useful to allow html help, maybe via a new "html_description" attribute parameter ?

Thanks !

**Comment by jbtronics** [comment]
You can pass arbitary options to the form types, via the `formOptions` options.
So something like `#[SettingsParameter(formType: TextType::class, formOptions: ["help_html" => true])]` should do what you want.

I do not think, that a dedicated option on the attribute would be really useful.

**Comment by aesislabs** [comment]
Ah yes, didn't see this options. It's perfect, thanks.
