### ISSUE TITLE
Example "FileType" option ?

### ISSUE THREAD

**Issue by aesislabs** [jbtronics/settings-bundle#19]
I tried to implement a custom type for uploading a file without success. The uploading part is working but to reload the actual file from the settings into the form I haven't had any success.

Some help would be appreciated.

Thanks !

**Comment by jeremybasolo** [comment]
Hi, I'm also interested for this feature. @aesislabs , how did you get the uploading part working ?
Many thanks

**Comment by jeremybasolo** [comment]
Actually managed to do it with a custom parameter type, @aesislabs if you're interested, I can share my solution with you.
