### ISSUE TITLE
Service "Jbtronics\SettingsBundle\Storage\ORMStorageAdapter" not found

### ISSUE THREAD

**Issue by pedrocasado** [jbtronics/settings-bundle#9]
ORMStorageAdapter is not being found because the following line throws ServiceNotFoundException.

https://github.com/jbtronics/settings-bundle/blob/9478d7663df2809aa55be78e05f522b973a153af/config/services.php#L275

Any thoughts why the service (doctrine.orm.entity_manager) is not being found? I've setup doctrine/symfony from a clean installation.

You can reproduce error here: https://github.com/pedrocasado/test-settings

**Comment by jbtronics** [comment]
Maybe you have to put the loading of the doctrine bundle before the settings-bundle in config/settings-bundle. I'm not hundred percent sure, if the loading order is important there.

**Comment by pedrocasado** [comment]
Order doesn't matter there. Just tested.

**Comment by jbtronics** [comment]
There was an issue in the detection logic of doctrine. This is now fixed with the latest commit.
